### ISSUE TITLE
[Bug]: Missing navigation button for the blog’s next page

### ISSUE THREAD

**Issue by scigy** [QualityUnit/liveagent-theme#347]
### Quick summary

Missing navigation (next page button) on the bottom of this page https://www.liveagent.com/blog/ and all its categories. looks like infinity loading stopped to work.  

### Steps to reproduce

1. Visit https://www.liveagent.com/blog/
2. Scroll to the bottom

### What you expected to happen

Next page button

### What actually happened

I don’t see it

### Browser

Google Chrome/Chromium

### Other notes

![Blog_issue](https://user-images.githubusercontent.com/93312141/180427189-ae3e796c-5915-4608-b154-f0fb2c223e5b.jpg)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by mvstepanek** [comment]
The issue is already fixed. For internal reporting, use the correct repository.
